[project]
name = "debias"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.12.0",
    "datasets>=4.4.1",
    "einops>=0.8.1",
    "torch>=2.9.1",
    "transformers>=4.57.1",
]
